### ISSUE TITLE
Support for Azure US Government Endpoints

### ISSUE THREAD

**Issue by Doctorbal** [Azure-Samples/storage-block-blob-dotnet-backup#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1.  Have an active Azure Government subscription.
2. Clone this repo.
3. Update the connection strings to point to the Azure US Government Storage Accounts.
4. You will see it fail with the below message as it defaults to *blob.core.windows.net* even when using the connection strings endpoint for Azure US Gov "core.usgovcloudapi.net".

### Any log messages given by the failure
>
```
Error while inserting to storage repository for this event. Event should come back to queue.Exception : Microsoft.WindowsAzure.Storage.StorageException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
--- End of inner exception stack trace ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at backup.core.Implementations.BlobRepository.<CopyBlobFromSourceToBackup>d__3.MoveNext() in C:\Users\Andreas-SL\Documents\git-repos\storage-block-blob-dotnet-backup\backup.core\Implementations\BlobRepository.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at backup.core.Implementations.StorageBackupWorker.<Run>d__6.MoveNext() in C:\Users\Andreas-SL\Documents\git-repos\storage-block-blob-dotnet-backup\backup.core\Implementations\StorageBackupWorker.cs:line 98
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:
 Event Data :{"topic":"/subscriptions/${SID}/resourceGroups/${RG}/providers/Microsoft.Storage/storageAccounts/${SA}","subject":"/blobServices/default/containers/${CONTAINER}/blobs/data/${ID}","eventType":"Microsoft.Storage.BlobCreated","eventTime":"2020-02-02T15:38:23.3953474Z","id":"${ID}","data":{"api":"PutBlockList","clientRequestId":"${ID}","requestId":"${ID}","eTag":"0x8D7A7F5F023DF75","contentType":"application/octet-stream","contentLength":43208704,"blobType":"BlockBlob","url":"https://$NAME.blob.core.windows.net/$NAME/data/$ID","sequencer":"$SEQUENCENUMBER","storageDiagnostics":{"batchId":"$BATCHID"}},"dataVersion":"","metadataVersion":"1"}
```

Not the following queue event created which is wrong:

```
{"topic":"/subscriptions/${SID}/resourceGroups/${RG}/providers/Microsoft.Storage/storageAccounts/${SA}","subject":"/blobServices/default/containers/${CONTAINER}/blobs/data/${ID}","eventType":"Microsoft.Storage.BlobCreated","eventTime":"2020-02-02T15:38:23.3953474Z","id":"${ID}","data":{"api":"PutBlockList","clientRequestId":"${ID}","requestId":"${ID}","eTag":"0x8D7A7F5F023DF75","contentType":"application/octet-stream","contentLength":43208704,"blobType":"BlockBlob","url":"https://$NAME.blob.core.windows.net/$NAME/data/$ID","sequencer":"$SEQUENCENUMBER","storageDiagnostics":{"batchId":"$BATCHID"}},"dataVersion":"","metadataVersion":"1"}
```

### Expected/desired behavior
> To successfully use the provided mechanism with Azure US Government storage endpoints.

### OS and Version?
> Using Windows 10 Pro with Visual Studio.

### Versions
> Latest Release; tag 84077.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Doctorbal** [comment]
I believe I came across a Azure US Government bug. The following PR addresses a workaround to get this to work in the Azure US Government instance - https://github.com/Azure-Samples/storage-block-blob-dotnet-backup/pull/6
